In [9]:
import os
print(os.getcwd())

/workspaces/CECS-399-499/data

In [16]:
import pandas as pd
df = pd.read_csv('../local_data/silver/EIA_pre_feature.csv', parse_dates=["timestamp"])

In [11]:
cols = [
    'demand_forecast_mwh',
    'actual_demand_mwh',
    'net_generation_mwh',
    'net_interchange_mwh'
]

mask = df[cols].isna().any(axis=1)
groups = (mask != mask.shift()).cumsum()

gap_details = []

for g, group in df[mask].groupby(groups):
    start = group.index[0]
    end = group.index[-1]
    length = len(group)
    
    missing_counts = group[cols].isna().sum()
    
    gap_details.append({
        'start': start,
        'end': end,
        'length_hours': length,
        'missing_counts': missing_counts.to_dict()
    })

gap_details

[{'start': np.int64(0),
  'end': np.int64(4),
  'length_hours': 5,
  'missing_counts': {'demand_forecast_mwh': 5,
   'actual_demand_mwh': 5,
   'net_generation_mwh': 5,
   'net_interchange_mwh': 5}},
 {'start': np.int64(7425),
  'end': np.int64(7445),
  'length_hours': 21,
  'missing_counts': {'demand_forecast_mwh': 0,
   'actual_demand_mwh': 21,
   'net_generation_mwh': 21,
   'net_interchange_mwh': 21}},
 {'start': np.int64(7449),
  'end': np.int64(7470),
  'length_hours': 22,
  'missing_counts': {'demand_forecast_mwh': 22,
   'actual_demand_mwh': 0,
   'net_generation_mwh': 0,
   'net_interchange_mwh': 0}},
 {'start': np.int64(10476),
  'end': np.int64(10493),
  'length_hours': 18,
  'missing_counts': {'demand_forecast_mwh': 18,
   'actual_demand_mwh': 0,
   'net_generation_mwh': 0,
   'net_interchange_mwh': 0}},
 {'start': np.int64(43801),
  'end': np.int64(43823),
  'length_hours': 23,
  'missing_counts': {'demand_forecast_mwh': 23,
   'actual_demand_mwh': 23,
   'net_generation_mwh': 23,
   'net_interchange_mwh': 23}}]

In [17]:
df.dtypes

timestamp              datetime64[us, UTC]
demand_forecast_mwh                float64
actual_demand_mwh                  float64
net_generation_mwh                 float64
net_interchange_mwh                float64
dtype: object

In [13]:
df.head(20)

,timestamp,demand_forecast_mwh,actual_demand_mwh,net_generation_mwh,net_interchange_mwh
0,2021-01-01 00:00:00+00:00,NaN,NaN,NaN,NaN
1,2021-01-01 01:00:00+00:00,NaN,NaN,NaN,NaN
2,2021-01-01 02:00:00+00:00,NaN,NaN,NaN,NaN
3,2021-01-01 03:00:00+00:00,NaN,NaN,NaN,NaN
4,2021-01-01 04:00:00+00:00,NaN,NaN,NaN,NaN
5,2021-01-01 05:00:00+00:00,14152.0,16270.0,16464.0,194.0
6,2021-01-01 06:00:00+00:00,13878.0,15673.0,15937.0,264.0
7,2021-01-01 07:00:00+00:00,14289.0,15105.0,15400.0,295.0
8,2021-01-01 08:00:00+00:00,13961.0,14618.0,14874.0,256.0
9,2021-01-01 09:00:00+00:00,13639.0,14299.0,14994.0,695.0
10,2021-01-01 10:00:00+00:00,13379.0,14087.0,14834.0,747.0
11,2021-01-01 11:00:00+00:00,13405.0,13923.0,14691.0,768.0
12,2021-01-01 12:00:00+00:00,13643.0,14012.0,14311.0,299.0
13,2021-01-01 13:00:00+00:00,13972.0,14242.0,14495.0,253.0
14,2021-01-01 14:00:00+00:00,14467.0,14260.0,14590.0,330.0
15,2021-01-01 15:00:00+00:00,14617.0,14605.0,14939.0,334.0
16,2021-01-01 16:00:00+00:00,14754.0,14877.0,15256.0,379.0
17,2021-01-01 17:00:00+00:00,14983.0,15243.0,15524.0,281.0
18,2021-01-01 18:00:00+00:00,14986.0,15543.0,15762.0,219.0
19,2021-01-01 19:00:00+00:00,14645.0,15338.0,15656.0,318.0

In [15]:
df = pd.read_csv('../local_data/silver/tn_selected_city_population_weights.csv')
df.head(10)

,city,Geographic Area,population_2021,population_2022,population_2023,population_2024,population_2025,weight_2021,weight_2022,weight_2023,weight_2024,weight_2025
0,chattanooga,"Chattanooga city, Tennessee",181885.0,185030.0,188080.0,191496.0,191496.0,0.079529,0.079860,0.080514,0.081273,0.081273
1,clarksville,"Clarksville city, Tennessee",170862.0,177020.0,181142.0,185690.0,185690.0,0.074709,0.076403,0.077544,0.078809,0.078809
2,franklin,"Franklin city, Tennessee",85972.0,87664.0,88816.0,89142.0,89142.0,0.037591,0.037836,0.038021,0.037833,0.037833
3,hendersonville,"Hendersonville city, Tennessee",62446.0,63064.0,63755.0,63947.0,63947.0,0.027304,0.027219,0.027292,0.027140,0.027140
4,jackson,"Jackson city, Tennessee",67881.0,68365.0,68391.0,69303.0,69303.0,0.029681,0.029507,0.029277,0.029413,0.029413
5,johnson_city,"Johnson City city, Tennessee",71145.0,72616.0,73447.0,73635.0,73635.0,0.031108,0.031341,0.031441,0.031252,0.031252
6,knoxville,"Knoxville city, Tennessee",192158.0,196210.0,197463.0,198722.0,198722.0,0.084021,0.084685,0.084530,0.084340,0.084340
7,memphis,"Memphis city, Tennessee",622541.0,618468.0,614587.0,610919.0,610919.0,0.272205,0.266934,0.263094,0.259281,0.259281
8,murfreesboro,"Murfreesboro city, Tennessee",156473.0,162595.0,166023.0,168387.0,168387.0,0.068417,0.070177,0.071072,0.071465,0.071465
9,nashville,Nashville-Davidson metropolitan government (ba...,675671.0,685903.0,694294.0,704963.0,704963.0,0.295435,0.296039,0.297215,0.299194,0.299194

In [18]:
df = pd.read_csv('../local_data/silver/tn_weighted_weather_21_25.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 43824 entries, 0 to 43823
Data columns (total 78 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   timestamp                            43824 non-null  str
 1   nashville_temperature_2m             43824 non-null  float64
 2   nashville_relative_humidity_2m       43824 non-null  int64
 3   nashville_precipitation              43824 non-null  float64
 4   nashville_cloud_cover                43824 non-null  int64
 5   nashville_wind_speed_10m             43824 non-null  float64
 6   nashville_shortwave_radiation        43824 non-null  float64
 7   memphis_temperature_2m               43824 non-null  float64
 8   memphis_relative_humidity_2m         43824 non-null  int64
 9   memphis_precipitation                43824 non-null  float64
 10  memphis_cloud_cover                  43824 non-null  int64
 11  memphis_wind_speed_10m               43824 non-null  float64
 12  memphis_shortwave_radiation          43824 non-null  float64
 13  knoxville_temperature_2m             43824 non-null  float64
 14  knoxville_relative_humidity_2m       43824 non-null  int64
 15  knoxville_precipitation              43824 non-null  float64
 16  knoxville_cloud_cover                43824 non-null  int64
 17  knoxville_wind_speed_10m             43824 non-null  float64
 18  knoxville_shortwave_radiation        43824 non-null  float64
 19  chattanooga_temperature_2m           43824 non-null  float64
 20  chattanooga_relative_humidity_2m     43824 non-null  int64
 21  chattanooga_precipitation            43824 non-null  float64
 22  chattanooga_cloud_cover              43824 non-null  int64
 23  chattanooga_wind_speed_10m           43824 non-null  float64
 24  chattanooga_shortwave_radiation      43824 non-null  float64
 25  clarksville_temperature_2m           43824 non-null  float64
 26  clarksville_relative_humidity_2m     43824 non-null  int64
 27  clarksville_precipitation            43824 non-null  float64
 28  clarksville_cloud_cover              43824 non-null  int64
 29  clarksville_wind_speed_10m           43824 non-null  float64
 30  clarksville_shortwave_radiation      43824 non-null  float64
 31  murfreesboro_temperature_2m          43824 non-null  float64
 32  murfreesboro_relative_humidity_2m    43824 non-null  int64
 33  murfreesboro_precipitation           43824 non-null  float64
 34  murfreesboro_cloud_cover             43824 non-null  int64
 35  murfreesboro_wind_speed_10m          43824 non-null  float64
 36  murfreesboro_shortwave_radiation     43824 non-null  float64
 37  franklin_temperature_2m              43824 non-null  float64
 38  franklin_relative_humidity_2m        43824 non-null  int64
 39  franklin_precipitation               43824 non-null  float64
 40  franklin_cloud_cover                 43824 non-null  int64
 41  franklin_wind_speed_10m              43824 non-null  float64
 42  franklin_shortwave_radiation         43824 non-null  float64
 43  johnson_city_temperature_2m          43824 non-null  float64
 44  johnson_city_relative_humidity_2m    43824 non-null  int64
 45  johnson_city_precipitation           43824 non-null  float64
 46  johnson_city_cloud_cover             43824 non-null  int64
 47  johnson_city_wind_speed_10m          43824 non-null  float64
 48  johnson_city_shortwave_radiation     43824 non-null  float64
 49  jackson_temperature_2m               43824 non-null  float64
 50  jackson_relative_humidity_2m         43824 non-null  int64
 51  jackson_precipitation                43824 non-null  float64
 52  jackson_cloud_cover                  43824 non-null  int64
 53  jackson_wind_speed_10m               43824 non-null  float64
 54  jackson_shortwave_radiation          43824 non-null  float64
 55  hendersonville_temperature_2m        43824 non-null  float64
 56  hendersonville_relative_humidity_2m  43824 non-null  int64
 57  hendersonville_precipitation         43824 non-null  float64
 58  hendersonville_cloud_cover           43824 non-null  int64
 59  hendersonville_wind_speed_10m        43824 non-null  float64
 60  hendersonville_shortwave_radiation   43824 non-null  float64
 61  year                                 43824 non-null  int64
 62  nashville_weight                     43824 non-null  float64
 63  memphis_weight                       43824 non-null  float64
 64  knoxville_weight                     43824 non-null  float64
 65  chattanooga_weight                   43824 non-null  float64
 66  clarksville_weight                   43824 non-null  float64
 67  murfreesboro_weight                  43824 non-null  float64
 68  franklin_weight                      43824 non-null  float64
 69  johnson_city_weight                  43824 non-null  float64
 70  jackson_weight                       43824 non-null  float64
 71  hendersonville_weight                43824 non-null  float64
 72  weighted_temperature_2m              43824 non-null  float64
 73  weighted_relative_humidity_2m        43824 non-null  float64
 74  weighted_precipitation               43824 non-null  float64
 75  weighted_cloud_cover                 43824 non-null  float64
 76  weighted_wind_speed_10m              43824 non-null  float64
 77  weighted_shortwave_radiation         43824 non-null  float64
dtypes: float64(56), int64(21), str(1)
memory usage: 27.1 MB

In [19]:
df = pd.read_csv('../local_data/bronze/doe417_2021_2023_clean.csv')
df.head()

,Month,Date Event Began,Time Event Began,Date of Restoration,Time of Restoration,Area Affected,NERC Region,Alert Criteria,Event Type,Demand Loss (MW),Number of Customers Affected,source_year,Event Month,event_start,event_end,duration_hours
0,January,01/01/2021,07:04:00,01/01/2021,07:05:00,California: Alameda County;,WECC,Physical attack that could potentially impact ...,Vandalism,0,0,2021,NaN,2021-01-01 07:04:00-06:00,2021-01-01 07:05:00-06:00,0.016667
1,January,01/02/2021,10:28:00,01/02/2021,10:29:00,California: Butte County;,WECC,Electrical System Separation (Islanding) where...,System Operations,8,5803,2021,NaN,2021-01-02 10:28:00-06:00,2021-01-02 10:29:00-06:00,0.016667
2,January,01/04/2021,10:34:00,01/04/2021,10:49:00,Pennsylvania:,RF,"Unexpected Transmission loss within its area, ...",Transmission Interruption,6,3825,2021,NaN,2021-01-04 10:34:00-06:00,2021-01-04 10:49:00-06:00,0.250000
3,January,01/08/2021,01:26:00,01/08/2021,02:45:00,Arkansas: Prairie County;,SERC,Damage or destruction of its Facility that res...,Sabotage,Unknown,1908,2021,NaN,2021-01-08 01:26:00-06:00,2021-01-08 02:45:00-06:00,1.316667
4,January,01/10/2021,22:44:00,01/13/2021,16:00:00,"Texas: Anderson County, Angelina County, Dalla...",TRE,"Loss of electric service to more than 50,000 c...",Severe Weather,Unknown,188000,2021,NaN,2021-01-10 22:44:00-06:00,2021-01-13 16:00:00-06:00,65.266667

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1125 entries, 0 to 1124
Data columns (total 16 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Month                         777 non-null    str
 1   Date Event Began              1093 non-null   str
 2   Time Event Began              1125 non-null   str
 3   Date of Restoration           1125 non-null   str
 4   Time of Restoration           1125 non-null   str
 5   Area Affected                 1125 non-null   str
 6   NERC Region                   1116 non-null   str
 7   Alert Criteria                1125 non-null   str
 8   Event Type                    1125 non-null   str
 9   Demand Loss (MW)              1125 non-null   str
 10  Number of Customers Affected  1125 non-null   str
 11  source_year                   1125 non-null   int64
 12  Event Month                   348 non-null    str
 13  event_start                   986 non-null    str
 14  event_end                     850 non-null    str
 15  duration_hours                848 non-null    float64
dtypes: float64(1), int64(1), str(14)
memory usage: 448.9 KB

In [22]:
df['Alert Criteria'][0]

'Physical attack that could potentially impact electric power system adequacy or reliability; or vandalism which targets components of any security systems.'

In [23]:
df['Alert Criteria'][1]

'Electrical System Separation (Islanding) where part or parts of power grid remain(s) operational in an otherwise blacked out area or within the partial failure of an integrated electrical system.'

In [27]:
df = pd.read_csv('../local_data/bronze/eagle_tn_daily_2021_2025.csv')
df.head(15)

      county        date  customers_out
0   Anderson  2021-01-01           25.0
1   Anderson  2021-01-02            NaN
2   Anderson  2021-01-04            4.0
3    Bedford  2021-01-01            1.0
4    Bedford  2021-01-02            3.0
5    Bedford  2021-01-04            1.0
6    Bledsoe  2021-01-01           18.0
7    Bledsoe  2021-01-02            NaN
8     Blount  2021-01-01           60.0
9     Blount  2021-01-02           31.0
10    Blount  2021-01-03           31.0
11    Blount  2021-01-04           46.0
12   Bradley  2021-01-01           43.0
13   Bradley  2021-01-02            3.0
14   Bradley  2021-01-03         1017.0

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12462 entries, 0 to 12461
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   county         12462 non-null  str
 1   date           12462 non-null  str
 2   customers_out  10979 non-null  float64
dtypes: float64(1), str(2)
memory usage: 497.3 KB